Repository n0-computer/iroh, pull requests merged in 2022-11, with the labels that each got.

#448 docs: update docs
  DEVELOPERS.md
  README.md
  quickstart.md
Labels: docs

#478 ref(lru-cache): Change lru cache crate to avoid vulnerable dependency
  iroh-p2p/Cargo.toml
  iroh-p2p/benches/lru_cache.rs
  iroh-p2p/src/behaviour/peer_manager.rs
Labels: bug

#483 ref(benches): Describe more ways of running benchmarks
  iroh-p2p/benches/lru_cache.rs
Labels: docs

#489 test(iroh-p2p): test interactions between multiple nodes
  iroh-p2p/Cargo.toml
  iroh-p2p/src/node.rs
  iroh-p2p/src/rpc.rs
  iroh-rpc-client/src/network.rs
  iroh-rpc-types/proto/p2p.proto
  iroh-rpc-types/src/p2p.rs
Labels: test, c-p2p

#507 fix(iroh-store): `put_many` bug
  iroh-store/Cargo.toml
  iroh-store/src/store.rs
Labels: fix

#516 tests: disable flakey test_dht
  iroh-p2p/src/node.rs
Labels: test

#513 fix: breadcrumb links in gateway directory template
  iroh-gateway/src/handlers.rs
Labels: fix

#497 refactor(ops): CI rework
  .circleci/config.yml
  .github/workflows/ci.yml
  Cargo.toml
Labels: ci, ops

#522 fix: iroh start service set construction
  iroh/src/fixture.rs
  iroh/src/run.rs
  iroh/src/services.rs
  iroh/tests/cli_tests.rs
  iroh/tests/cmd/start_status_stop.trycmd
Labels: fix

#527 fix: convert v0 -> v1 before base32 conversion
  iroh-resolver/src/content_loader.rs
Labels: fix, c-resolver

#537 fix(`iroh-p2p`): implement full local lookup
  iroh-api/src/p2p.rs
  iroh-p2p/src/behaviour.rs
  iroh-p2p/src/behaviour/peer_manager.rs
  iroh-p2p/src/node.rs
  iroh-p2p/src/rpc.rs
  iroh-rpc-client/src/network.rs
  iroh-rpc-types/proto/p2p.proto
  iroh-rpc-types/src/p2p.rs
Labels: c-p2p, fix

#552 chore(ci): disable codecov comments
  codecov.yml
Labels: ci

#553 chore(ci): add iroh-one to binary builds
  .github/workflows/ci.yml
Labels: ci
