Repository n0-computer/iroh, pull requests merged in 2022-10, with the labels that each got.

#289 property based tests for unixfs
  iroh-resolver/Cargo.toml
  iroh-resolver/src/resolver.rs
  iroh-resolver/src/unixfs_builder.rs
Labels: c-unixfs

#305 docs: small formatting fix
  DEVELOPERS.md
Labels: docs

#304 Gateway: Fetch recursive DAG as CAR
  iroh-car/src/header.rs
  iroh-gateway/Cargo.toml
  iroh-gateway/src/client.rs
  iroh-gateway/src/constants.rs
  iroh-gateway/src/core.rs
  iroh-gateway/src/handlers.rs
  iroh-resolver/src/resolver.rs
Labels: c-gateway

#327 fix: allow `Raw` as `UnixfsType`
  iroh-resolver/src/resolver.rs
Labels: fix

#332 fix(iroh-gateway): add `FileType::Raw` option
  iroh-gateway/src/client.rs
  iroh-gateway/src/handlers.rs
  iroh-resolver/src/resolver.rs
Labels: fix

#333 use xtasks for release builds and man page generation
  .cargo/config
  Cargo.toml
  xtask/Cargo.toml
  xtask/README.md
  xtask/src/main.rs
Labels: docs

#328 initial directory listing support
  iroh-gateway/Cargo.toml
  iroh-gateway/assets/404.html
  iroh-gateway/assets/dir_list.html
  iroh-gateway/assets/icons.css
  iroh-gateway/assets/style.css
  iroh-gateway/src/config.rs
  iroh-gateway/src/core.rs
  iroh-gateway/src/handlers.rs
  iroh-gateway/src/templates.rs
  iroh-one/src/config.rs
  iroh-util/Cargo.toml
  iroh-util/src/human.rs
  iroh-util/src/lib.rs
Labels: feat, c-gateway

#319 gateway: spec parity
  iroh-gateway/Cargo.toml
  iroh-gateway/src/bad_bits.rs
  iroh-gateway/src/client.rs
  iroh-gateway/src/config.rs
  iroh-gateway/src/constants.rs
  iroh-gateway/src/core.rs
  iroh-gateway/src/error.rs
  iroh-gateway/src/handlers.rs
  iroh-gateway/src/headers.rs
  iroh-gateway/src/response.rs
  iroh-one/src/content_loader.rs
  iroh-resolver/src/resolver.rs
  iroh-share/src/p2p_node.rs
Labels: c-gateway

#342 feat: improve CLI texts and flags
  iroh/src/run.rs
Labels: c-ctl

#330 feat: range request support
  iroh-api/src/api.rs
  iroh-gateway/src/client.rs
  iroh-gateway/src/handlers.rs
  iroh-gateway/src/headers.rs
  iroh-resolver/src/resolver.rs
  iroh-resolver/src/unixfs.rs
  iroh-resolver/src/unixfs_builder.rs
  iroh-share/src/receiver.rs
Labels: c-gateway

#348 docs: add full help text for `lookup`, `connect`, `get`, `p2p`, and `iroh` commands
  iroh/src/doc.rs
  iroh/src/lib.rs
  iroh/src/p2p.rs
  iroh/src/run.rs
Labels: docs, c-ctl

#337 feat(unixfs): add symlink support
  iroh-api/src/api.rs
  iroh-api/src/api_ext.rs
  iroh-resolver/src/resolver.rs
  iroh-resolver/src/unixfs_builder.rs
  iroh/src/fixture.rs
  iroh/tests/cli_tests.rs
  iroh/tests/cmd/get_cid_explicit_output_path_success.out/explicit/a/exists
  iroh/tests/cmd/get_cid_success.out/QmP8jTG1m9GSDJLCbeWhVSVgEzCPPwXRdCRuJtQ5Tz9Kc9/a/exists
  iroh/tests/cmd/get_ipfs_path_success.out/QmP8jTG1m9GSDJLCbeWhVSVgEzCPPwXRdCRuJtQ5Tz9Kc9/a/exists
  iroh/tests/cmd/get_unwrapped_symlink.out/QmP8jTG1m9GSDJLCbeWhVSVgEzCPPwXRdCRuJtQ5Tz9Kc9
  iroh/tests/cmd/get_unwrapped_symlink.trycmd
  iroh/tests/cmd/get_wrapped_symlink.out/QmP8jTG1m9GSDJLCbeWhVSVgEzCPPwXRdCRuJtQ5Tz9Kc9/symlink.txt
  iroh/tests/cmd/get_wrapped_symlink.trycmd
Labels: feat, c-unixfs

#350 gateway: spec compliance part 2
  iroh-gateway/Cargo.toml
  iroh-gateway/src/bad_bits.rs
  iroh-gateway/src/config.rs
  iroh-gateway/src/error.rs
  iroh-gateway/src/handlers.rs
  iroh-gateway/src/headers.rs
Labels: c-gateway

#363 ci: fix builds & add platforms
  .circleci/config.yml
  .github/ci.yml
Labels: ci

#364 ci: GHA
  .circleci/config.yml
  .github/workflows/ci.yml
  Cargo.toml
  iroh-bitswap/src/peer_task_queue.rs
  iroh-gateway/src/templates.rs
Labels: ci

#374 fix: move bitswap msg counters out of encode/decode
  iroh-bitswap/src/lib.rs
  iroh-bitswap/src/network.rs
  iroh-bitswap/src/protocol.rs
Labels: metrics, fix

#387 fix: gha disk space hacks
  .github/workflows/ci.yml
Labels: ci

#360 iroh start & stop commands
  Cargo.toml
  iroh-gateway/src/main.rs
  iroh-localops/Cargo.toml
  iroh-localops/REAME.md
  iroh-localops/src/lib.rs
  iroh-localops/src/process.rs
  iroh-one/src/main.rs
  iroh-p2p/src/main.rs
  iroh-rpc-client/src/status.rs
  iroh-store/src/main.rs
  iroh-util/Cargo.toml
  iroh-util/src/exitcodes.rs
  iroh-util/src/lib.rs
  iroh-util/src/lock.rs
  iroh/Cargo.toml
  iroh/src/doc.rs
  iroh/src/lib.rs
  iroh/src/run.rs
  iroh/src/services.rs
  iroh/src/status.rs
Labels: c-ctl

#372 feat(p2p): implement `connect` and `lookup`
  iroh-api/Cargo.toml
  iroh-api/src/api_ext.rs
  iroh-api/src/lib.rs
  iroh-api/src/p2p.rs
  iroh-one/Cargo.toml
  iroh-one/src/config.rs
  iroh-p2p/src/node.rs
  iroh-p2p/src/rpc.rs
  iroh-rpc-client/src/lib.rs
  iroh-rpc-client/src/network.rs
  iroh-rpc-types/proto/p2p.proto
  iroh-rpc-types/src/p2p.rs
  iroh/src/fixture.rs
  iroh/src/p2p.rs
  iroh/tests/cmd/lookup.trycmd
Labels: c-p2p, c-ctl

#398 start/stop accept arguments, start defaults to {store,gateway}
  iroh/src/doc.rs
  iroh/src/run.rs
  iroh/src/services.rs
Labels: c-ctl

#402 feat: p2p api service calls with a p2p-specific error, better feedback
  iroh-api/Cargo.toml
  iroh-api/src/error.rs
  iroh-api/src/lib.rs
  iroh-api/src/p2p.rs
  iroh/src/main.rs
Labels: c-ctl

#397 `iroh p2p peers`: command to list peers
  iroh-api/src/p2p.rs
  iroh/src/doc.rs
  iroh/src/p2p.rs
Labels: c-ctl

#404 feat: connection pooling
  iroh-api/src/api.rs
  iroh-gateway/src/bad_bits.rs
  iroh-gateway/src/core.rs
  iroh-one/src/config.rs
  iroh-one/src/content_loader.rs
  iroh-p2p/src/node.rs
  iroh-resolver/src/resolver.rs
  iroh-rpc-client/src/client.rs
  iroh-rpc-client/src/config.rs
  iroh-share/src/p2p_node.rs
  iroh-store/benches/rpc.rs
Labels: perf

#403 race on gateway
  iroh-gateway/src/cli.rs
  iroh-gateway/src/config.rs
  iroh-gateway/src/main.rs
  iroh-one/src/config.rs
  iroh-one/src/lib.rs
  iroh-one/src/main.rs
  iroh-resolver/Cargo.toml
  iroh-resolver/src/lib.rs
  iroh-resolver/src/racing.rs
Labels: c-gateway

#408 fix(resolver): ipld, double-fetching, and trailing slash fixes
  iroh-resolver/src/resolver.rs
Labels: fix, c-resolver

#414 fix(resolver): handle trailing slashes in the path with more sense
  iroh-resolver/src/resolver.rs
Labels: fix

#415 feat: offline adding
  iroh/src/run.rs
  iroh/src/services.rs
Labels: c-ctl

#422 fix: properly saves filenames for hamt dirs
  iroh-resolver/src/resolver.rs
Labels: bug, fix

#424 long description for add command
  iroh/src/doc.rs
Labels: docs

#427 B5/output cleanup
  iroh-util/src/lock.rs
  iroh/src/doc.rs
  iroh/src/p2p.rs
  iroh/tests/cmd/lookup.trycmd
Labels: c-ctl

#431 fix: error when someone tries to start an unknown service
  iroh/src/services.rs
Labels: fix

#436 ci: fix release builds
  .circleci/config.yml
  .github/workflows/ci.yml
Labels: ci
