Repository n0-computer/iroh, pull requests merged in 2022-08, with the labels that each got.

#169 ci: mac builds
  .circleci/config.yml
Labels: ci

#174 fix: default off metrics & tracing
  iroh-gateway/src/main.rs
  iroh-metrics/src/config.rs
  iroh-metrics/src/lib.rs
  iroh-p2p/src/main.rs
  iroh-p2p/src/node.rs
  iroh-share/src/p2p_node.rs
  iroh-store/src/main.rs
Labels: metrics

#175 feat: ctl ci
  .circleci/config.yml
Labels: ci

#173 fix: fix builds
  iroh-gateway/src/config.rs
  iroh-p2p/src/config.rs
  iroh-store/src/config.rs
Labels: ci, fix

#184 fix: ci release aarch64 linux
  .circleci/config.yml
Labels: ci

#186 ci: self hosted mac runner
  .circleci/config.yml
Labels: ci, ops

#190 ci: fix linux aarch64 builds
  .circleci/config.yml
  Cargo.toml
Labels: ci

#191 ci: fix mac release builds
  .circleci/config.yml
Labels: ci

#172 feat: bad bits implementation
  iroh-gateway/Cargo.toml
  iroh-gateway/src/bad_bits.rs
  iroh-gateway/src/config.rs
  iroh-gateway/src/core.rs
  iroh-gateway/src/lib.rs
  iroh-gateway/src/main.rs
Labels: c-gateway

#199 fix: hamt directory listings
  iroh-gateway/Cargo.toml
  iroh-gateway/src/client.rs
  iroh-gateway/src/core.rs
  iroh-resolver/Cargo.toml
  iroh-resolver/src/hamt.rs
  iroh-resolver/src/resolver.rs
  iroh-resolver/src/unixfs.rs
  iroh-share/src/lib.rs
  iroh-share/src/main.rs
  iroh-share/src/receiver.rs
Labels: bug
