Repository n0-computer/iroh, pull requests merged in 2022-05, with the labels that each got.

#26 feat: rpc client that can handle out-going commands and incoming requests
  .gitignore
  iroh-rpc/Cargo.toml
  iroh-rpc/src/behaviour/mod.rs
  iroh-rpc/src/behaviour/rpc.rs
  iroh-rpc/src/builder.rs
  iroh-rpc/src/client.rs
  iroh-rpc/src/commands.rs
  iroh-rpc/src/error.rs
  iroh-rpc/src/handler.rs
  iroh-rpc/src/lib.rs
  iroh-rpc/src/serde.rs
  iroh-rpc/src/server.rs
  iroh-rpc/src/stream.rs
  iroh-rpc/src/swarm.rs
  iroh/src/main.rs
Labels: feat

#76 fix: avoid 0 divisions
  iroh-gateway/src/client.rs
Labels: bug

#85 fix: tracing on request level
  iroh-gateway/Cargo.toml
  iroh-gateway/src/core.rs
Labels: metrics
