Repository n0-computer/iroh, pull requests merged in 2023-10, with the labels that each got.

#1562 chore(baomap): drop all baomap logging to debug or lower
  iroh/src/baomap/flat.rs
  iroh/src/baomap/mem.rs
Labels: c-iroh

#1563 feat: `doc import` & `doc export` commands
  iroh/src/client.rs
  iroh/src/commands/sync.rs
  iroh/src/node.rs
  iroh/src/rpc_protocol.rs
  iroh/src/sync_engine/rpc.rs
  iroh/src/util/fs.rs
Labels: c-iroh, c-iroh-sync

#1629 fix: `doc export` exports the latest entry at a given key
  iroh/src/commands/sync.rs
Labels: fix

#1660 iroh-bytes: Get api improvements
  iroh-bytes/src/get.rs
  iroh-bytes/src/protocol/range_spec.rs
  iroh-bytes/src/util.rs
  iroh/src/commands/get.rs
Labels: feat, refactor, c-iroh-bytes

#1697 docs: `test_run_mesh_client` documentation
  iroh-net/src/derp/http/client.rs
Labels: docs

#1756 chore: makes `SyncReason` public (as expected)
  iroh/src/sync_engine.rs
Labels: c-api, c-iroh-sync

#1737 feat(ci): CI improvements
  .github/workflows/ci.yml
  .github/workflows/netsim.yml
  iroh/tests/cli.rs
Labels: ci

#1761 chore: split test and check steps into workspace and per crate
  .github/workflows/ci.yml
  .github/workflows/test.sh
  iroh-bytes/Cargo.toml
Labels: ci

#1762 fix(ci): avoid sccache on linux aarch64 builds
  .github/workflows/ci.yml
Labels: ci

#1763 fix: release builds
  .github/workflows/ci.yml
Labels: ci
