Repository n0-computer/iroh, pull requests merged in 2023-07, with the labels that each got.

#1174 fix: cross builds
  .github/workflows/ci.yml
Labels: ci

#1155 test: add tests for the main derper endpoints
  iroh-net/src/bin/derper.rs
  iroh-net/src/hp/derp/http/client.rs
  iroh-net/src/hp/derp/http/mesh_clients.rs
  iroh-net/src/hp/derp/http/server.rs
Labels: test, c-derper

#1171 docs: fill out derp documentation
  iroh-net/src/hp/derp.rs
  iroh-net/src/hp/derp/client.rs
  iroh-net/src/hp/derp/client_conn.rs
  iroh-net/src/hp/derp/http.rs
  iroh-net/src/hp/derp/http/client.rs
  iroh-net/src/hp/derp/http/mesh_clients.rs
  iroh-net/src/hp/derp/http/server.rs
  iroh-net/src/hp/derp/map.rs
  iroh-net/src/hp/derp/server.rs
  iroh-net/src/hp/derp/types.rs
Labels: docs, c-derper

#1186 feat(ci): allow running netsim from another branch
  .github/workflows/netsim.yml
Labels: ci

#1173 refactor: pluggable metrics
  Cargo.lock
  iroh-metrics/Cargo.toml
  iroh-metrics/src/core.rs
  iroh-metrics/src/iroh.rs
  iroh-metrics/src/lib.rs
  iroh-metrics/src/macros.rs
  iroh-metrics/src/magicsock.rs
  iroh-metrics/src/metrics.rs
  iroh-metrics/src/netcheck.rs
  iroh-metrics/src/portmap.rs
  iroh-metrics/src/service.rs
  iroh-net/src/hp/magicsock/conn.rs
  iroh-net/src/hp/magicsock/derp_actor.rs
  iroh-net/src/hp/netcheck.rs
  iroh-net/src/hp/portmapper.rs
  iroh-net/src/hp/portmapper/mapping.rs
  iroh-net/src/hp/portmapper/upnp.rs
  iroh/src/commands.rs
  iroh/src/commands/doctor.rs
  iroh/src/lib.rs
  iroh/src/metrics.rs
Labels: refactor, c-iroh-metrics

#1205 fix: netsim branch CI default
  .github/workflows/netsim.yml
Labels: bug

#1206 chore: pause release builds
  .github/workflows/ci.yml
Labels: ci

#1208 fix: default netsim branch
  .github/workflows/netsim.yml
Labels: ci

#1214 fix: make sure to clean up any lingering processes
  .github/workflows/ci.yml
  .github/workflows/netsim.yml
Labels: ci

#1243 chore(ci): bring back release builds
  .github/workflows/ci.yml
Labels: ci

#1260 feat: add metrics to the derp server
  iroh-metrics/src/lib.rs
  iroh-metrics/src/metrics.rs
  iroh-net/docs/derp_regions.md
  iroh-net/docs/local_derper.md
  iroh-net/src/hp/derp.rs
  iroh-net/src/hp/derp/client_conn.rs
  iroh-net/src/hp/derp/clients.rs
  iroh-net/src/hp/derp/http/client.rs
  iroh-net/src/hp/derp/metrics.rs
  iroh-net/src/hp/derp/server.rs
  iroh-net/src/hp/magicsock.rs
  iroh-net/src/hp/magicsock/conn.rs
  iroh-net/src/hp/magicsock/derp_actor.rs
  iroh-net/src/hp/magicsock/metrics.rs
  iroh-net/src/hp/netcheck.rs
  iroh-net/src/hp/netcheck/metrics.rs
  iroh-net/src/hp/netcheck/reportgen.rs
  iroh-net/src/hp/portmapper.rs
  iroh-net/src/hp/portmapper/mapping.rs
  iroh-net/src/hp/portmapper/metrics.rs
  iroh-net/src/hp/portmapper/upnp.rs
  iroh-net/src/lib.rs
  iroh-net/src/metrics.rs
  iroh/src/commands.rs
  iroh/src/commands/doctor.rs
Labels: feat, metrics, hole punching, c-derper, c-iroh-metrics

#1262 Nits in the derp docs
  iroh-net/src/hp/derp.rs
  iroh-net/src/hp/derp/http.rs
Labels: docs, hole punching, c-derper

#1268 fix: enable derp metrics
  iroh-net/src/bin/derper.rs
Labels: metrics, c-derper

#1198 chore(*): contributors guide
  CONTRIBUTING.md
  code_of_conduct.md
Labels: docs

#1270 chore(ci): add ffi bindings to CI
  .github/workflows/bindings.yml
  .github/workflows/netsim.yml
  iroh-ffi/iroh.h
Labels: ci, c-ffi

#1304 chore(ci): ensure external contributors don't fail CI on report dumps
  .github/workflows/ci.yml
  .github/workflows/netsim.yml
Labels: ci

#1308 feat: enable metrics server on sync REPL
  iroh/examples/sync.rs
Labels: metrics, c-iroh

#1319 add stun specific metrics to the Derper
  iroh-net/src/bin/derper.rs
Labels: metrics, c-derper
