Repository n0-computer/iroh, pull requests merged in 2023-12, with the labels that each got.

#1862 feat: usage metrics reporting
  Cargo.lock
  iroh-metrics/Cargo.toml
  iroh-metrics/src/core.rs
  iroh-metrics/src/lib.rs
  iroh-net/src/derp/server.rs
Labels: feat, metrics, c-iroh-metrics

#1880 chore(docs): update derp IP for EU region
  iroh-net/docs/derp_regions.md
Labels: bug

#1883 chore(ci): split release builds from regular CI flows
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: ci

#1895 refactor(iroh-net): make `ControlMsg` public
  iroh-net/src/magicsock.rs
  iroh-net/src/magicsock/peer_map.rs
  iroh-net/src/magicsock/peer_map/endpoint.rs
Labels: c-iroh-net

#1884 chore(ci): test derper deploy flow
  .github/ansible/redeploy-derper.yml
  .github/workflows/test_derper.yml
Labels: ci

#1923 chore(netsim): disable netsim prometheus reports
  .github/workflows/ci.yml
  .github/workflows/netsim.yml
Labels: ci
