Repository n0-computer/iroh, pull requests merged in 2023-06, with the labels that each got.

#1077 fix tls bugs & create an `hp::derp::http::server::Server`
  Cargo.lock
  Cargo.toml
  src/bin/derper.rs
  src/config.rs
  src/doctor.rs
  src/get.rs
  src/hp.rs
  src/hp/derp.rs
  src/hp/derp/client.rs
  src/hp/derp/client_conn.rs
  src/hp/derp/clients.rs
  src/hp/derp/http.rs
  src/hp/derp/http/client.rs
  src/hp/derp/http/server.rs
  src/hp/derp/server.rs
  src/hp/derp/types.rs
  src/hp/dns.rs
  src/hp/magicsock/conn.rs
  src/hp/magicsock/derp_actor.rs
  src/hp/netcheck.rs
  src/main.rs
  src/net/interfaces/bsd.rs
  src/provider/ticket.rs
  src/tls.rs
  src/util.rs
Labels: hole punching

#1110 fix: don't crash the derper
  src/hp/derp/client_conn.rs
  src/hp/derp/http/server.rs
Labels: fix

#1113 fix: don't spam re-connect attempts if something goes wrong when connecting to a derp server
  src/hp/derp/client_conn.rs
  src/hp/derp/http/client.rs
Labels: fix, hole punching

#1118 refactor: split metrics off into its own crate
  .github/workflows/ci.yml
  .github/workflows/netsim.yml
  Cargo.lock
  Cargo.toml
  iroh-metrics/Cargo.toml
  iroh-metrics/README.md
  iroh-metrics/src/core.rs
  iroh-metrics/src/iroh.rs
  iroh-metrics/src/lib.rs
  iroh-metrics/src/macros.rs
  iroh-metrics/src/magicsock.rs
  iroh-metrics/src/metrics.rs
  iroh-metrics/src/netcheck.rs
  iroh-metrics/src/service.rs
  iroh-net/Cargo.toml
  iroh-net/src/hp/magicsock/conn.rs
  iroh-net/src/hp/magicsock/derp_actor.rs
  iroh-net/src/hp/netcheck.rs
  iroh-net/src/lib.rs
  iroh/Cargo.toml
  iroh/src/doctor.rs
  iroh/src/main.rs
Labels: refactor

#1128 fix: improve connectivity
  .github/workflows/ci.yml
  .github/workflows/netsim.yml
  Cargo.lock
  iroh-net/Cargo.toml
  iroh-net/src/client.rs
  iroh-net/src/hp/cfg.rs
  iroh-net/src/hp/derp/http.rs
  iroh-net/src/hp/derp/http/client.rs
  iroh-net/src/hp/derp/map.rs
  iroh-net/src/hp/magicsock/conn.rs
  iroh-net/src/hp/magicsock/endpoint.rs
  iroh-net/src/hp/magicsock/rebinding_conn.rs
  iroh-net/src/hp/magicsock/udp_actor.rs
  iroh-net/src/hp/netcheck.rs
  iroh-net/src/hp/stun.rs
  iroh/src/commands/doctor.rs
  iroh/src/config.rs
  iroh/tests/cli.rs
Labels: hole punching

#1130 feat: derp mesh network & derper cli cleanup
  iroh-net/src/bin/derper.rs
  iroh-net/src/hp/derp/client.rs
  iroh-net/src/hp/derp/http.rs
  iroh-net/src/hp/derp/http/client.rs
  iroh-net/src/hp/derp/http/mesh_clients.rs
  iroh-net/src/hp/derp/http/server.rs
  iroh-net/src/hp/derp/server.rs
  iroh-net/src/hp/magicsock/conn.rs
  iroh-net/src/hp/magicsock/derp_actor.rs
Labels: feat, hole punching
