Repository n0-computer/iroh, pull requests merged in 2024-05, with the labels that each got.

#2234 feat(iroh-net)!: Improve initial connection latency
  Cargo.lock
  iroh-blobs/Cargo.toml
  iroh-blobs/examples/provide-bytes.rs
  iroh-blobs/src/provider.rs
  iroh-cli/Cargo.toml
  iroh-docs/Cargo.toml
  iroh-docs/src/net.rs
  iroh-gossip/Cargo.toml
  iroh-gossip/examples/chat.rs
  iroh-net/Cargo.toml
  iroh-net/bench/Cargo.toml
  iroh-net/examples/listen-unreliable.rs
  iroh-net/examples/listen.rs
  iroh-net/src/disco.rs
  iroh-net/src/magic_endpoint.rs
  iroh-net/src/magic_endpoint/rtt_actor.rs
  iroh-net/src/magicsock.rs
  iroh-net/src/magicsock/node_map/best_addr.rs
  iroh-net/src/magicsock/node_map/node_state.rs
  iroh/Cargo.toml
  iroh/src/docs_engine.rs
  iroh/src/docs_engine/live.rs
  iroh/src/node/builder.rs
Labels: feat, c-iroh-net

#2206 feat(iroh-cli): add doctor plot
  Cargo.lock
  iroh-cli/Cargo.toml
  iroh-cli/src/commands/doctor.rs
Labels: metrics

#2186 feat: iroh-perf
  .github/workflows/ci.yml
  .github/workflows/tests.yaml
  Cargo.lock
  iroh-net/bench/Cargo.toml
  iroh-net/bench/src/bin/bulk.rs
  iroh-net/bench/src/iroh.rs
  iroh-net/bench/src/lib.rs
  iroh-net/bench/src/quinn.rs
  iroh-net/bench/src/s2n.rs
  iroh-net/bench/src/stats.rs
Labels: perf, benchmarks
