Repository n0-computer/iroh, pull requests merged in 2024-11, with the labels that each got.

#2885 fix(metrics): allow external crates to encode their metrics
  iroh-metrics/src/core.rs
Labels: metrics

#2886 fix(ci): better error reporting on netsim fails
  .github/workflows/netsim_runner.yaml
Labels: ci

#2890 chore(ci): easy manual builds for binaries
  .github/workflows/release.yml
Labels: ci

#2893 chore(ci): fix uploads of release artifacts again
  .github/workflows/release.yml
Labels: ci

#2898 chore(ci): fix for asset bundles
  .github/workflows/release.yml
Labels: ci

#2956 fix(ci): try to reuse msys2 dep
  .github/workflows/tests.yaml
Labels: ci

#2882 ref(iroh-net)!: Make Endpoint::close not consume self
  iroh-net/src/endpoint.rs
  iroh-router/src/router.rs
Labels: c-iroh-net
